service: api-util

plugins:
  # - serverless-offline-ssm
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-plugin-split-stacks

custom:  
  stage: ${opt:stage, 'dev'}
  layer: 
    stack: ${file(../env.yml):layer.stack}
    name:
      libs: ${file(../env.yml):layer.name.libs}
      nodejs: ${file(../env.yml):layer.name.nodejs}
  warmup:
    name: ${self:custom.stage}-api-util-warmer
    events:
      - schedule:
          rate: cron(0/10 * * * ? *)
    payload:
      source: 'api-util-warmer'
  splitStacks:
    perFunction: false
    perType: false
    perGroupFunction: false

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ap-northeast-2

  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-sns-crawler-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-sns-crawler-ApiGatewayRestApiRootResourceId

  # These environment variables are made available to our functions under process.env.
  environment:
    DB_HOST: ${ssm:/${self:custom.stage}/crawlerdb/host~true}
    DB_USER: ${ssm:/${self:custom.stage}/crawlerdb/user~true}
    DB_PASSWORD: ${ssm:/${self:custom.stage}/crawlerdb/password~true}
    DB_DATABASE: ${ssm:/${self:custom.stage}/crawlerdb/database~true}


  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

package:
  exclude:
    - node_modules/**
    - README.md
    - package-lock.json

functions:
  - ${file(./resources/function-util.yml)}